db = db.getSiblingDB('products_db');

db.products.drop();

db.products.insertMany([
  {
    name: "Smartphone Samsung Galaxy A55",
    slug: "smartphone-samsung-galaxy-a55",
    description: "Téléphone intelligent avec écran Super AMOLED 6,6 pouces, appareil photo 50 MP et batterie 5000 mAh.",
    price: NumberDecimal("399.99"),
    currency: "EUR",
    category: "Électronique",
    images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600"],
    stock: 25,
    attributes: { couleur: "Bleu Sombre", stockage: "128 Go", ram: "8 Go" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Laptop Dell Inspiron 15",
    slug: "laptop-dell-inspiron-15",
    description: "Ordinateur portable 15,6 pouces, Intel Core i5 12ème génération, 16 Go RAM, SSD 512 Go.",
    price: NumberDecimal("749.99"),
    currency: "EUR",
    category: "Électronique",
    images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600"],
    stock: 12,
    attributes: { couleur: "Argent", processeur: "Intel Core i5", ram: "16 Go", stockage: "512 Go SSD" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Casque Audio Sony WH-1000XM5",
    slug: "casque-sony-wh1000xm5",
    description: "Casque sans fil à réduction de bruit active, autonomie 30 heures, son Hi-Res.",
    price: NumberDecimal("299.99"),
    currency: "EUR",
    category: "Électronique",
    images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600"],
    stock: 30,
    attributes: { couleur: "Noir", connexion: "Bluetooth 5.2", autonomie: "30h" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "T-shirt Coton Bio Homme",
    slug: "tshirt-coton-bio-homme",
    description: "T-shirt 100% coton biologique, coupe régulière, disponible en plusieurs couleurs.",
    price: NumberDecimal("24.99"),
    currency: "EUR",
    category: "Vêtements",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600"],
    stock: 100,
    attributes: { matiere: "Coton bio 100%", couleur: "Blanc", tailles: ["XS", "S", "M", "L", "XL", "XXL"] },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Jean Slim Femme",
    slug: "jean-slim-femme",
    description: "Jean slim taille haute en denim stretch, confortable et élégant pour toutes les occasions.",
    price: NumberDecimal("49.99"),
    currency: "EUR",
    category: "Vêtements",
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600"],
    stock: 75,
    attributes: { couleur: "Bleu indigo", matiere: "Denim stretch", coupe: "Slim" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Veste en Cuir Femme",
    slug: "veste-cuir-femme",
    description: "Veste en cuir véritable, style biker moderne, doublure intérieure confortable.",
    price: NumberDecimal("189.99"),
    currency: "EUR",
    category: "Vêtements",
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600"],
    stock: 20,
    attributes: { couleur: "Noir", matiere: "Cuir véritable", style: "Biker" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Canapé 3 Places Scandinave",
    slug: "canape-3-places-scandinave",
    description: "Canapé design scandinave en tissu gris, structure en bois massif, très confortable.",
    price: NumberDecimal("599.99"),
    currency: "EUR",
    category: "Maison",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600"],
    stock: 8,
    attributes: { couleur: "Gris chiné", matiere: "Tissu", dimensions: "220x85x80 cm", places: 3 },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Lampe de Bureau LED",
    slug: "lampe-bureau-led",
    description: "Lampe de bureau LED avec 5 niveaux de luminosité et 3 températures de couleur, port USB intégré.",
    price: NumberDecimal("39.99"),
    currency: "EUR",
    category: "Maison",
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600"],
    stock: 45,
    attributes: { couleur: "Blanc", puissance: "12W", connexion: "USB-C" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Plante Monstera Deliciosa",
    slug: "plante-monstera-deliciosa",
    description: "Grande plante d'intérieur tropicale, feuilles découpées caractéristiques. Pot inclus.",
    price: NumberDecimal("34.99"),
    currency: "EUR",
    category: "Maison",
    images: ["https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600"],
    stock: 15,
    attributes: { hauteur: "60-80 cm", pot: "Inclus 18cm", entretien: "Facile" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Tapis de Yoga Antidérapant",
    slug: "tapis-yoga-antiderapant",
    description: "Tapis de yoga 6mm en TPE écologique, antidérapant, avec sangle de transport.",
    price: NumberDecimal("29.99"),
    currency: "EUR",
    category: "Sport",
    images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600"],
    stock: 60,
    attributes: { couleur: "Violet", epaisseur: "6mm", matiere: "TPE", dimensions: "183x61 cm" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Montre Connectée Garmin Forerunner",
    slug: "montre-garmin-forerunner",
    description: "Montre GPS de running avec suivi de fréquence cardiaque, VO2 max et plans d'entraînement.",
    price: NumberDecimal("249.99"),
    currency: "EUR",
    category: "Sport",
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600"],
    stock: 18,
    attributes: { couleur: "Noir/Rouge", gps: true, autonomie: "14 jours", etancheite: "5ATM" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Bouteille Isotherme Inox 1L",
    slug: "bouteille-isotherme-inox-1l",
    description: "Bouteille isotherme en acier inoxydable, maintient froid 24h et chaud 12h. Sans BPA.",
    price: NumberDecimal("19.99"),
    currency: "EUR",
    category: "Sport",
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600"],
    stock: 80,
    attributes: { couleur: "Vert forêt", contenance: "1L", matiere: "Inox 18/8" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Roman 'L'Étranger' - Albert Camus",
    slug: "roman-letranger-camus",
    description: "Chef-d'œuvre de la littérature française, édition poche. Un classique incontournable.",
    price: NumberDecimal("8.99"),
    currency: "EUR",
    category: "Livres",
    images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600"],
    stock: 200,
    attributes: { auteur: "Albert Camus", pages: 186, langue: "Français", format: "Poche" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Dictionnaire Français-Anglais Larousse",
    slug: "dictionnaire-larousse-fr-en",
    description: "Dictionnaire bilingue Larousse, 90 000 mots et expressions, édition 2024.",
    price: NumberDecimal("22.99"),
    currency: "EUR",
    category: "Livres",
    images: ["https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600"],
    stock: 50,
    attributes: { editeur: "Larousse", pages: 1200, langue: "Français/Anglais", edition: "2024" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Cafetière Expresso Delonghi",
    slug: "cafetiere-expresso-delonghi",
    description: "Machine à expresso avec mousseur à lait, pression 15 bars, réservoir 1,5L amovible.",
    price: NumberDecimal("159.99"),
    currency: "EUR",
    category: "Cuisine",
    images: ["https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600"],
    stock: 22,
    attributes: { couleur: "Noir", pression: "15 bars", reservoir: "1.5L", puissance: "1350W" },
    active: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);

print("Seed data inserted: " + db.products.countDocuments() + " produits");
